name: Code Master

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@v1.0.13
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Korean
          PROMPT: This is a code developed with React. Based on clean code principles, please provide a concise overall evaluation of any code defects in the modifications, with no more than 3 points for the evaluation. Please include specific examples and suggestions for improvement.
          MODEL: gpt-3.5-turbo
          max_tokens: 4096
