name: Code Master

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@v1.0.13
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Korean
          PROMPT: This is a React-based code. Please provide a comprehensive evaluation of the entire modifications based on clean code and algorithm standards on a scale of 1 to 5 in increments of 0.5.
          MODEL: gpt-3.5-turbo
          max_tokens: 4096
